### ISSUE TITLE
Move zoom-in sampled propagation of coronagraphs to `coronagraph.py`

### ISSUE THREAD

**Issue by ivalaginja** [johanmazoyer/Asterix#123]
> ok I see the problem. Even if you do that, I get a "circular import" warning when I do a "pylint Asterix/". this is not critical if we're careful I think, we've discuss that (hcipy have tons of these circular imports) but would be better if we can avoid that.
> 
> When you do  
`from Asterix.optics import`
you actually import all optics functions and you get lot of circular imports. What I meant by targeted is something like :
`import Asterix.optics.phase_amplitude_functions as phase_ampl`
you limit a lof the circular import because you only import `phase_amplitude_functions`.
> 
> However, this is a "true" circular import because `phase_amplitude_functions` need the mft, so you need to import `propagation_function`. It will probabaly not broke the stuff because you only need the mft in a `sine_cosine_basis` which is very specific, but I'm not sure in all cases.
> 
> Eventually the solution is to move `prop_fpm_regional_sampling` to coronagraph.py. I already asked you that, I think it make sense, because other propagation functions (MFT, FFT, Frensnel) in this file are very general, they are called by a lot of other optical instruments or even by other functions (like `sine_cosine_basis` or others in utils) because you always need fft-like functions. On the other hand `prop_fpm_regional_sampling` is only coronagraph oriented

_Originally posted by @johanmazoyer in https://github.com/johanmazoyer/Asterix/pull/119#discussion_r1030278827_

**Comment by johanmazoyer** [comment]
ok
