### ISSUE TITLE
Sampling requirement for estimation is too restrictive

### ISSUE THREAD

**Issue by ivalaginja** [johanmazoyer/Asterix#163]
The estimator currently requires a sampling of >3 after binning of the science plane:
https://github.com/johanmazoyer/Asterix/blob/6085cb543b17d6dd731db523bb7cd3eb1b6acf86/Asterix/wfsc/estimator.py#L100

This is too restrictive for the shortest wavelength on THD2, which is 637 nm and samples the science plane at 5.9 pixels per lam/D. When binning by the standard factor of 2 for the estimator, this still gives a sampling of 2.95 which is sufficient.

If this error is supposed to guard against sub-Nyquist sampling, then >2 should be enough. If there is any other reason for the current >3 requirement, please let me know @johanmazoyer .

**Comment by johanmazoyer** [comment]
ok let me think about this. I think we did that because we were afraid that Estim_sampling < 3 would loose too much information. Another possibility is to avoid binning altogether. You should test that.
