### ISSUE TITLE
Problem with the DM3_filename_grid_actu file

### ISSUE THREAD

**Issue by johanmazoyer** [johanmazoyer/Asterix#37]
In the last version of the code I realized that something pitch was wrong since April 2021 when I updated DM3_filename_grid_actu file from 
DM3_Grid_actu_Pixel156mic.fits
to
DM3_Grid_actu_Pixel141mic.fits

This had for effect to reduce the pitch, an easy way to see it is that too many actuators are currently in the pupil.
<img width="675" alt="Screenshot 2021-09-16 at 16 05 23" src="https://user-images.githubusercontent.com/22528508/133626700-4537858e-648f-4da4-b545-752a8f500a84.png">

**With DM3_Grid_actu_Pixel156mic.fits** file the extreme actuators horizontally in the pupil (first ones to have their center in the pupils) are 80 and 944 which correspond to 27 Actuators in the pupil, which is expected (8.23 / 0.3 = 27.4)

![with156](https://user-images.githubusercontent.com/22528508/133632985-d8ba236c-3101-48bd-bff7-481579758b49.png)

**With DM3_Grid_actu_Pixel141mic.fits** file the extreme actuators horizontally in the pupil (first ones to have their center in the pupils) are 48 and 976 which correspond to 29 Actuators in the pupil, which is very too much.

![with141](https://user-images.githubusercontent.com/22528508/133632980-d6c6893f-fcfe-4e48-8a91-cd2be7df7b2b.png)

I could not find any hardcoded parameters, the parameters are read in the header of these fits and must therefore be wrong but I do not know really well this part of the code so I open this issue

**Comment by johanmazoyer** [comment]
Currently switching back to DM3_Grid_actu_Pixel141mic.fits in the master, waiting for instructoin by RGa.

Investigating if the same issue arose for DM1.

**Comment by rgalicher** [comment]
Salut,
Il y a une histoire qu'une grille était pour la pupille de 8.1mm et l'autre pour 8.23mm. À verifier.
En tout cas, la grille 156 est sortie de mesures que j'ai faites sur le banc pour l'orientation et le pitch.
En revanche, je n'avais pas vérifié les actionneurs extrêmes. Peut-être à faire sur le banc.

**Comment by rgalicher** [comment]
ps : bien vu !

**Comment by johanmazoyer** [comment]
hehe, j'ai mis ça en "issue" pour garder une trace sous le coude pcq c'etait important, mais c'est pas urgent, on en parle quand tu reviens. 

Je vais voir si on peut par la refaire proprement avec Pierre avec la 8.3 et je ferais attention en la mettant dans Asterix. Mais du coup ca explique peut être pourquoi l'EFC ça marchait pas bien !

**Comment by rgalicher** [comment]
on peut fermer ce point qui est obsolète n'est pas ?
