### ISSUE TITLE
Move `roundpupil()` to `pupil.py`

### ISSUE THREAD

**Issue by ivalaginja** [johanmazoyer/Asterix#93]
Maybe, we talked about this but this discussion definitely needs #86 to be merged first.

**Comment by johanmazoyer** [comment]
Yes, I thought about it and agree is a good idea

**Comment by johanmazoyer** [comment]
I've tried and it's super tricky

Major problem, we need round pupil every where, including in the mother class of pupil, OpticalSystem. So if we need to call pupil to call round pupil we create tons of circular important
